github_api_token: YOUR_GITHUB_API_TOKEN
plot_color: blue
plot_title: Distribution of Hooray Reactions
plot_x_axis_title: Hooray
plot_y_axis_title: Other Events
figure_size:
  width: 10
  height: 6
default_save_path: static/plot.png

